function expandTech(a){for(var b=[document.getElementById("expdlintech1"),document.getElementById("expdlintech2"),document.getElementById("expdlintech3")],e=0;e<3;e++)if(b[e].id==a.id){b.splice(e,1);break}expand(a,b,inTechSubAnimationRunning)}function shrinkTech(){var a=[document.getElementById("expdlintech1"),document.getElementById("expdlintech2"),document.getElementById("expdlintech3")];shrink(a,inTechSubAnimationRunning)}
function showLineTech(){var a=[document.getElementById("expdlintechhr"),document.getElementById("expdlintechtr")];showLine(a,inTechAnimationRunning)}function hideLineTech(){var a=[document.getElementById("expdlintechhr"),document.getElementById("expdlintechtr")];hideLine(a,inTechAnimationRunning)}function showLineSport(){var a=[document.getElementById("expdlinsporthr"),document.getElementById("expdlinsporttr")];showLine(a,inSportAnimationRunning)}
function hideLineSport(){var a=[document.getElementById("expdlinsporthr"),document.getElementById("expdlinsporttr")];hideLine(a,inSportAnimationRunning)}function showLine(a,b){var e=[$(a[0]).width()/$(a[0]).parent().width()*100,$(a[1]).height()];a[0].style.display="block";animate(a,e,[90,220],15,15,[function(f,c){f.style.width=c+"%"},function(f,c){f.style.height=c+"px"}],b)}
function hideLine(a,b){var e=[$(a[0]).width()/$(a[0]).parent().width()*100,$(a[1]).height()];animate(a,e,[0,195],15,15,[function(f,c){f.style.width=c+"%"},function(f,c){f.style.height=c+"px"}],b);setTimeout(function(){a[0].style.display="none"},100)}function expandSport(a){for(var b=[document.getElementById("expdlinsport1"),document.getElementById("expdlinsport2"),document.getElementById("expdlinsport3")],e=0;e<3;e++)if(b[e].id==a.id){b.splice(e,1);break}expand(a,b,inSportSubAnimationRunning)}
function shrinkSport(){var a=[document.getElementById("expdlinsport1"),document.getElementById("expdlinsport2"),document.getElementById("expdlinsport3")];shrink(a,inSportSubAnimationRunning)}
function expand(a,b,e){var f=[a,b[0],b[1],a.getElementsByTagName("img")[0],b[0].getElementsByTagName("img")[0],b[1].getElementsByTagName("img")[0]];a=[$(a).width(),$(b[0]).width(),$(b[1]).width(),$(a.getElementsByTagName("img")[0]).width(),$(b[0].getElementsByTagName("img")[0]).width(),$(b[1].getElementsByTagName("img")[0]).width()];animate(f,a,[175,138,138,150,113,113],30,18,[function(c,d){c.style.width=d+"px"},function(c,d){c.style.width=d+"px"},function(c,d){c.style.width=d+"px"},function(c,d){c.style.width=
    d+"px"},function(c,d){c.style.width=d+"px"},function(c,d){c.style.width=d+"px"}],e)}
function shrink(a,b){var e=[a[0],a[1],a[2],a[0].getElementsByTagName("img")[0],a[1].getElementsByTagName("img")[0],a[2].getElementsByTagName("img")[0]],f=[$(a[0]).width(),$(a[1]).width(),$(a[2]).width(),$(a[0].getElementsByTagName("img")[0]).width(),$(a[1].getElementsByTagName("img")[0]).width(),$(a[2].getElementsByTagName("img")[0]).width()];animate(e,f,[150,150,150,125,125,125],30,18,[function(c,d){c.style.width=d+"px"},function(c,d){c.style.width=d+"px"},function(c,d){c.style.width=d+"px"},function(c,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           d){c.style.width=d+"px"},function(c,d){c.style.width=d+"px"},function(c,d){c.style.width=d+"px"}],b)}var softElems,webElems,softExpanded={value:false},webExpanded={value:false};function showSoftRadial(){var a=softElems=[document.getElementById("radprsoftmod1"),document.getElementById("radprsoftmod2"),document.getElementById("radprsoftmod3"),document.getElementById("radprsoftmod4")];showRadial(document.getElementById("radprsoftimg"),a,prSoftAnimationRunning,softExpanded)}
function showWebRadial(){var a=webElems=[document.getElementById("radprwebmod1"),document.getElementById("radprwebmod2"),document.getElementById("radprwebmod3")];showRadial(document.getElementById("radprwebimg"),a,prWebAnimationRunning,webExpanded)}function hideSoftRadial(){var a=softElems;hideRadial(document.getElementById("radprsoftimg"),a,prSoftAnimationRunning,softExpanded)}
function hideWebRadial(){var a=webElems;hideRadial(document.getElementById("radprwebimg"),a,prWebAnimationRunning,webExpanded)}
function focusRadial(a,b,e){b=b.slice(0);for(var f=[a,a],c=[$(a).width(),parseInt(a.getAttribute("radial-distance"))],d=[95,130],i=[function(h,j){h.width=j},function(h,j){placeInRadial(h,parseInt(h.getAttribute("radial-rotation")),j)}],g=0;g<b.length;g++)if(b[g].id==a.id){b.splice(g,1);break}for(g=0;g<b.length;g++){f.push(b[g]);c.push($(b[g]).width());d.push(75);i.push(function(h,j){h.width=j});f.push(b[g]);c.push(parseInt(b[g].getAttribute("radial-distance")));d.push(110);i.push(function(h,j){placeInRadial(h,
    parseInt(h.getAttribute("radial-rotation")),j)})}animate(f,c,d,15,9,i,e)}function unfocusRadials(a,b){for(var e=[],f=[],c=[],d=[],i=0;i<a.length;i++){e.push(a[i]);f.push($(a[i]).width());c.push(75);d.push(function(g,h){g.width=h});e.push(a[i]);f.push(parseInt(a[i].getAttribute("radial-distance")));c.push(110);d.push(function(g,h){placeInRadial(g,parseInt(g.getAttribute("radial-rotation")),h)})}animate(e,f,c,15,9,d,b)}
function showRadial(a,b,e,f){var c=[a];a=[$(a).width()];animateRadial(c,a,[160],[function(d,i){d.width=i}],e,b,110,100);setTimeout(function(){f.value=true},50/3*5)}function hideRadial(a,b,e,f){var c=[a];a=[$(a).width()];f.value=false;animateRadial(c,a,[225],[function(d,i){d.width=i}],e,b,90,0)}
function animateRadial(a,b,e,f,c,d,i,g){for(var h=0;h<d.length;h++){a.push(d[h]);b.push($(d[h]).css("opacity")*100);e.push(g);f.push(function(j,l){j.style.opacity=l/100});a.push(d[h]);b.push(parseInt(d[h].getAttribute("radial-distance")));e.push(i);f.push(function(j,l){placeInRadial(j,parseInt(j.getAttribute("radial-rotation")),l)})}animate(a,b,e,30,18,f,c)}
var inTechSubAnimationRunning={value:0},inTechAnimationRunning={value:0},inSportSubAnimationRunning={value:0},inSportAnimationRunning={value:0},inSocialAnimationRunning={value:0},prSoftAnimationRunning={value:0},prSoftAnimationRadialRunning={value:0},prWebAnimationRunning={value:0},prWebAnimationRadialRunning={value:0};
function animate(a,b,e,f,c,d,i){var g=setInterval(function(){if(i.value==0||i.value==g){h=0;i.value=g;if(l>100||i.value!=g){i.value=g;clearInterval(g)}else{l+=c;for(var k=0;k<a.length;k++)j[k]=l/100*(e[k]-b[k])+b[k];for(k=0;k<j.length;k++)d[k](a[k],j[k])}}else if(h>0){i.value=g;h=0}else clearInterval(g)},f),h=1,j=[],l=0}
$(document).ready(function(){$("#expdlintech1").mouseenter(function(){expandTech(this)});$("#expdlintech2").mouseenter(function(){expandTech(this)});$("#expdlintech3").mouseenter(function(){expandTech(this)});$("#expdlintech").mouseenter(function(){showLineTech()});$("#expdlintech").mouseleave(function(){shrinkTech();hideLineTech()});$("#expdlinsport1").mouseenter(function(){expandSport(this)});$("#expdlinsport2").mouseenter(function(){expandSport(this)});$("#expdlinsport3").mouseenter(function(){expandSport(this)});
    $("#expdlinsport").mouseenter(function(){showLineSport()});$("#expdlinsport").mouseleave(function(){shrinkSport();hideLineSport()});$("#expdlso1").mouseenter(function(){showSocial(this)});$("#expdlso2").mouseenter(function(){showSocial(this)});$("#expdlso3").mouseenter(function(){showSocial(this)});$("#expdlso").mouseleave(function(){hideImage()});$("#radprsofttd").mouseenter(function(){showSoftRadial()});$("#radprsofttd").mouseleave(function(){hideSoftRadial()});$("#radprwebtd").mouseenter(function(){showWebRadial()});
    $("#radprwebtd").mouseleave(function(){hideWebRadial()});$("#radprwebmod1").mouseenter(function(){webExpanded.value&&focusRadial(this,webElems,prWebAnimationRadialRunning)});$("#radprwebmod2").mouseenter(function(){webExpanded.value&&focusRadial(this,webElems,prWebAnimationRadialRunning)});$("#radprwebmod3").mouseenter(function(){webExpanded.value&&focusRadial(this,webElems,prWebAnimationRadialRunning)});$("#radprwebmod1").mouseleave(function(){unfocusRadials(webElems,prWebAnimationRadialRunning)});
    $("#radprwebmod2").mouseleave(function(){unfocusRadials(webElems,prWebAnimationRadialRunning)});$("#radprwebmod3").mouseleave(function(){unfocusRadials(webElems,prWebAnimationRadialRunning)});$("#radprsoftmod1").mouseenter(function(){softExpanded.value&&focusRadial(this,softElems,prSoftAnimationRadialRunning)});$("#radprsoftmod2").mouseenter(function(){softExpanded.value&&focusRadial(this,softElems,prSoftAnimationRadialRunning)});$("#radprsoftmod3").mouseenter(function(){softExpanded.value&&focusRadial(this,
        softElems,prSoftAnimationRadialRunning)});$("#radprsoftmod4").mouseenter(function(){softExpanded.value&&focusRadial(this,softElems,prSoftAnimationRadialRunning)});$("#radprsoftmod1").mouseleave(function(){unfocusRadials(softElems,prSoftAnimationRadialRunning)});$("#radprsoftmod2").mouseleave(function(){unfocusRadials(softElems,prSoftAnimationRadialRunning)});$("#radprsoftmod3").mouseleave(function(){unfocusRadials(softElems,prSoftAnimationRadialRunning)});$("#radprsoftmod4").mouseleave(function(){unfocusRadials(softElems,
        prSoftAnimationRadialRunning)})});function placeInRadial(a,b,e){var f=radialPoint(b-90,{x:207,y:127.5},e);a.style.left=f.x-a.width/2+"px";a.style.top=f.y-a.height/2+"px";a.setAttribute("radial-distance",e);a.setAttribute("radial-rotation",b)}function radialPoint(a,b,e){return{x:b.x+Math.cos(a/180*Math.PI)*e,y:b.y+Math.sin(a/180*Math.PI)*e}};
function showImage(a,b,c){var d=[a,b[0],b[1]],e=[100*$(a).css("opacity"),100*$(b[0]).css("opacity"),100*$(b[1]).css("opacity")],f=[100,10,10],g=[function(a,b){a.style.opacity=b/100},function(a,b){a.style.opacity=b/100},function(a,b){a.style.opacity=b/100}];animate(d,e,f,30,18,g,c)}function hideImage(){var a=[document.getElementById("expdlso1").getElementsByClassName("switchimg")[0],document.getElementById("expdlso2").getElementsByClassName("switchimg")[0],document.getElementById("expdlso3").getElementsByClassName("switchimg")[0]],b=[100*$(a[0]).css("opacity"),100*$(a[1]).css("opacity"),100*$(a[2]).css("opacity")],c=[0,0,0],d=[function(a,b){a.style.opacity=b/100},function(a,b){a.style.opacity=b/100},function(a,b){a.style.opacity=b/100}];animate(a,b,c,30,16,d,inSocialAnimationRunning)}function showSocial(a){for(var b=[document.getElementById("expdlso1"),document.getElementById("expdlso2"),document.getElementById("expdlso3")],c=0;c<3;c++)if(b[c].id==a.id){b.splice(c,1);break}for(var c=0;c<b.length;c++)b[c]=b[c].getElementsByClassName("switchimg")[0];showImage(a.getElementsByClassName("switchimg")[0],b,inSocialAnimationRunning)}